# email = "user@domain.tld"
# facebook = "yourfacebookusername"
github = "abansod"
gitlab = "abansod"
linkedin = "in/akshaybansod"
# stackoverflow = "yourstackoverflowuserid"
twitter = "@AkshayB04"
# weibo = "yourweibousername"
# zhihu = "yourzhihuusername"
# instagram = "yourinstagramusername"
# quora = "yourquorausername"
# tumblr = "yourtumblrusername"
# reddit = "yourredditusername"
# telegram = "yourtelegramusername"
# qq = "yourqqnumber"
dockerhub = "abansod04"
# bitbucket = "yourbitbucketworkspaceid"
# kaggle = "yourkaggleusername"
# medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm = "yourlastfmusername"
# bilibili = "yourbilibiliuserid"
# youtube = "youryoutubechannelid"
# discord = "yourdiscordinvitecode"
# discourse = "https://yourforum.tld"
# facebookgroup = "yourfacebookgroupname"
# tiktok = "yourtiktokusername"
